#!/bin/sh
# Copyright (C) 2011  INRIA and Microsoft Corporation

BASEDIR="`pwd`"
TOOLDIR="$BASEDIR/TOOLS"
SUFFIX=_test.tla

usage () {
    echo "usage: do_tests [options] <dir>" >&2
    exit 3
}

export PM="$BASEDIR/bin/tlapm --stretch 10"
export LOGFILE="$BASEDIR/tests.log"
echo "###### `date '+%Y-%m-%d %H:%M:%S'` $0 $@" >>"$LOGFILE"

while [ $# -ge 1 ]; do
  case $1 in
    --suffix=*) SUFFIX="${1##--suffix=}"; shift; continue;;
    -*) usage;;
  esac

  find "$1" -name '*.tlaps' -prune -o -name "*${SUFFIX}" -print
  shift

done | {

  total=0
  success=0
  fail=0

  while read f; do
    total=`expr $total + 1`
    printf "  %s " "$f"
    export FILE="`basename $f`"
    export DIR="`dirname $f`"
    echo "    $f" >>"$LOGFILE"
    if [ "`basename "$DIR"`" = "smt_tests" ]; then
        ARGS="--method smt"
    else
        ARGS=
    fi
    export TLAPM="$PM $ARGS"

    echo | (cd $DIR; $TOOLDIR/do_one_test "$FILE" "$TOOLDIR/separator" \
                                          "$FILE.out" "$FILE.err" \
                                          >"$FILE.out" 2>"$FILE.err")
    case $? in
      0) echo ok
         success=`expr $success + 1`
         rm -f "$f.out" "$f.err"
         ;;
      *) echo FAILED
         fail=`expr $fail + 1`
         ;;
    esac
    rm -rf ${f}ps
  done

  echo
  echo "total:   $total"
  echo "success: $success"
  echo "failure: $fail"

  case $fail in
    0) exit 0;;
    *) echo
       echo "**** WARNING: SOME TESTS FAILED ****"
       echo
       exit 3;;
  esac
}
